index.html, script.js
=> Added Tailwind css and added one table

index.html, script.js
=> Created CO PO Table

script.js
=> Added validation code

index.html, script.js
=> Added a field where user can input COs, POs etc.

index.html
=> Edited the form

index.html, script.js
=> fixed validation code

script.js
=> Minor changes done

index.html
=> Made minor changes

index.html, script.js
Removed the average table, edited the PO, CO and PSO table, removed some validations
=> Removed the average table, edited the PO CO table, removed some validations

index.html
=> Added minor changes

index.html
=> Interchanged CO an PSO div

script.js
=> Edited the display code for CO, PO input

script.js
=> Minor changes

index.html
=> Codechange

index.html, script.js
=> Added number of students in the form

script.js
=> Minor change

index.html
=> Added G division to the course form

script.js
=> Reloading page is disabled once data is added

index.html
=> added new print button

index.html
=> Added script

index.html, script.js
=> Vchangecode

index.html
=> done minor changes dont worry

index.html
=> Refactored the HTML code

script.js
=> Refactored the JS code

index.html, script.js
=> Minor bugs fixed
